export const SET_CITY = "SET_CITY";

export const GET_SEARCH_FIELD = "GET_SEARCH_FIELD"

export const FETCH_FORECAST_PENDING = "FETCH_FORECAST_PENDING";

export const FETCH_FORECAST_SUCCESS = "FETCH_FORECAST_SUCCESS";

export const FETCH_FORECAST_FAILURE = "FETCH_FORECAST_FAILURE";